[custom]

; --- 1. 设置规则标志位 (告诉流量该怎么走) ---
; 拦截满天飞的广告
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
; 局域网直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
; 微软直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list
; 中国域名直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
; 中国 IP 直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
; 著名的被墙网站走代理
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFW.list
; Telegram 走代理
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Telegram.list

; --- 2. 设置分组标志位 (建立你的节点文件夹) ---
; ★ 核心神级代码：把你的 300 个 CF 节点全部装进这个组！
custom_proxy_group=🚀 节点选择`select`.*
; 直连组
custom_proxy_group=🎯 全球直连`select`[]DIRECT
; 广告拦截组
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
; 兜底组 (如果上面的规则都不匹配，剩下的流量全走代理)
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连

; --- 3. 基础设置 ---
enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
